### ISSUE TITLE
ABAP

### ISSUE THREAD

**Issue by larshp** [springernature/sap-utilities#1]
hi,
if you change the extension of the file from "cls" to "abap", then github will automatically syntax highlight the file as ABAP, and the repository will be recognized to contain ABAP code instead of OpenEdge ABL

**Comment by lnryan** [comment]
@larshp  - thanks for the tip. what i am unsure of is how then to differentiate the different types of abap assets - such as abap function modules, reports, etc? do they all get the abap suffix? do you know who maintains these suffix identities for github?

**Comment by larshp** [comment]
Only the .abap will syntax highlight abap code as abap on github, this is maintained by github in the linguist project, see
https://github.com/github/linguist/blob/71656116794a8561ae6e29299185599d82fcf7b9/lib/linguist/languages.yml#L34

There is no standard for ABAP files since the objects normally reside inside the database. But you can take a look at https://github.com/larshp/abapGit it might help serializing the objects to files. It names everything as .abap, but prepends the TADIR-OBJECT type. 

Examples:
- zfoobar.prog.abap
- zcl_json_parser.clas.abap
- zif_something.intf.abap

**Comment by lnryan** [comment]
ah cool. i was thinking of something similar but using `tadir-object` is smart. thx!
